on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Calculate Semver
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          fallbackTag: "0.0.1"
      - id: create-tag
        name: Create Git Tag
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.semver.outputs.next }} -m "Release v${{ steps.semver.outputs.nextStrict }}"
          git push origin ${{ steps.semver.outputs.next }}

      - id: goreleaser-snapshot
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --parallelism=1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
